//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public Material()
        {
            this.Operation = new HashSet<Operation>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int IdMaterial { get; set; }
        public string name { get; set; }
        public int weight { get; set; }
        public string manufacturer { get; set; }
        public int cost { get; set; }
        public int quantity { get; set; }
    
        public virtual ICollection<Operation> Operation { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
