//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public Operation()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int IdOperation { get; set; }
        public string type { get; set; }
        public int numberInvoice { get; set; }
        public int cost { get; set; }
        public int idWorker { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual ICollection<Material> Material { get; set; }
    }
}
